providers:
  docker:
    exposedByDefault: false
    endpoint: "unix:///var/run/docker.sock"
  file:
    directory: /etc/traefik/dynamic
    watch: true
entryPoints:
  web:
    address: ':80'
api:
  insecure: true
log:
  level: DEBUG